name: yata_flutter
description: A new Flutter project.
publish_to: "none"
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  file_picker: ^3.0.0
  file_saver: ^0.0.4
  filesystem_picker: 2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  flutter_markdown: ^0.6.0
  flutter_math_fork: ^0.3.0+2
  flutter_riverpod: ^0.13.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  markdown: ^4.0.0
  open_file: ^3.1.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.2
dev_dependencies:
  build_runner: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  json_serializable: ^4.0.0
  lint: ^1.5.3
  linter: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
