name: flutter_playground
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  file_picker: ^3.0.0
  filesystem_picker: 2.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.0
  flutter_math_fork: ^0.3.3+1
  flutter_riverpod: ^0.14.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  markdown: ^4.0.0
  open_file: ^3.1.0
  path_provider: ^2.0.1
  permission_handler: ^8.1.1
  ffi: ^1.0.0
  universal_io: ^2.0.4
  file_saver: ^0.0.10
  url_launcher: ^6.0.9
  # url_launcher: ^6.0.9
dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  lint: ^1.5.3
  linter: ^1.0.0
  ffigen: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - pkg/flutter_playground.js
    - pkg/flutter_playground_bg.wasm
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
  # plugin:
  #   platforms:
  #     web:
  #       pluginClass: FlutterPlaygroundWeb
  #       fileName: flutter_playground_web.dart
ffigen:
  name: MarkdownRust
  description: Bindings to the Rust library
  output: lib/ffi.dart
  llvm-path:
    - ./
  headers:
    entry-points:
      - bindings.h
