// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to the Rust library
class MarkdownRust {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MarkdownRust(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MarkdownRust.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Parses a Markdown string and returns a JSON string of the AST.
  /// The returned pointer should be freed by [free_string].
  ffi.Pointer<ffi.Int8> parse_markdown(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown(
      ptr,
    );
  }

  late final _parse_markdown_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown>>('parse_markdown');
  late final _dart_parse_markdown _parse_markdown =
      _parse_markdown_ptr.asFunction<_dart_parse_markdown>();

  /// Parses a Markdown string and returns HTML.
  /// The returned pointer should be freed by [free_string].
  ffi.Pointer<ffi.Int8> parse_markdown_xml(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown_xml(
      ptr,
    );
  }

  late final _parse_markdown_xml_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown_xml>>('parse_markdown_xml');
  late final _dart_parse_markdown_xml _parse_markdown_xml =
      _parse_markdown_xml_ptr.asFunction<_dart_parse_markdown_xml>();

  /// Parses a Markdown string and returns a list of [CElement]s.
  /// The returned pointer should be freed by [free_elements].
  ffi.Pointer<Slice_CElement> parse_markdown_ast(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown_ast(
      ptr,
    );
  }

  late final _parse_markdown_ast_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown_ast>>('parse_markdown_ast');
  late final _dart_parse_markdown_ast _parse_markdown_ast =
      _parse_markdown_ast_ptr.asFunction<_dart_parse_markdown_ast>();

  /// Frees the [Slice] created by [parse_markdown_ast].
  void free_elements(
    ffi.Pointer<Slice_CElement> ptr,
  ) {
    return _free_elements(
      ptr,
    );
  }

  late final _free_elements_ptr =
      _lookup<ffi.NativeFunction<_c_free_elements>>('free_elements');
  late final _dart_free_elements _free_elements =
      _free_elements_ptr.asFunction<_dart_free_elements>();

  /// Similar to [parse_markdown], but uses the algorithm from [parse_markdown_ast].
  /// The returned pointer should be freed by [free_string].
  ffi.Pointer<ffi.Int8> parse_markdown_ast_json(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown_ast_json(
      ptr,
    );
  }

  late final _parse_markdown_ast_json_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown_ast_json>>(
          'parse_markdown_ast_json');
  late final _dart_parse_markdown_ast_json _parse_markdown_ast_json =
      _parse_markdown_ast_json_ptr.asFunction<_dart_parse_markdown_ast_json>();

  /// Common string destructor intended to be called by the Dart side.
  void free_string(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _free_string(
      ptr,
    );
  }

  late final _free_string_ptr =
      _lookup<ffi.NativeFunction<_c_free_string>>('free_string');
  late final _dart_free_string _free_string =
      _free_string_ptr.asFunction<_dart_free_string>();

  /// Exposes the [CElement] as a text node if it is one, or null otherwise.
  ffi.Pointer<ffi.Int8> as_text(
    ffi.Pointer<CElement> el,
  ) {
    return _as_text(
      el,
    );
  }

  late final _as_text_ptr = _lookup<ffi.NativeFunction<_c_as_text>>('as_text');
  late final _dart_as_text _as_text = _as_text_ptr.asFunction<_dart_as_text>();

  /// Exposes the [CElement] as a [CHtmlTag] if it is one, or null otherwise.
  ffi.Pointer<CHtmlTag> as_tag(
    ffi.Pointer<CElement> el,
  ) {
    return _as_tag(
      el,
    );
  }

  late final _as_tag_ptr = _lookup<ffi.NativeFunction<_c_as_tag>>('as_tag');
  late final _dart_as_tag _as_tag = _as_tag_ptr.asFunction<_dart_as_tag>();
}

class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int32> __val;
}

/// Tag for [CElement].
abstract class CTag {
  /// [Element::Text]
  static const int Text = 0;

  /// [Element::Tag]
  static const int Tag = 1;
}

abstract class Tags {
  static const int Paragraph = 0;
  static const int H1 = 1;
  static const int H2 = 2;
  static const int H3 = 3;
  static const int H4 = 4;
  static const int H5 = 5;
  static const int H6 = 6;
  static const int Blockquote = 7;
  static const int Pre = 8;
  static const int OrderedList = 9;
  static const int UnorderedList = 10;
  static const int ListItem = 11;
  static const int Table = 12;
  static const int TableRow = 13;
  static const int TableCell = 14;
  static const int TableHeaderCell = 15;
  static const int Emphasis = 16;
  static const int Strong = 17;
  static const int Strikethrough = 18;
  static const int Anchor = 19;
  static const int Image = 20;
  static const int Code = 21;
  static const int HardBreak = 22;
  static const int Ruler = 23;
  static const int Checkbox = 24;
  static const int Math = 25;
}

abstract class TextAlign {
  static const int None = 0;
  static const int Left = 1;
  static const int Center = 2;
  static const int Right = 3;
}

/// Dart does not support enum strcts (20210721),
/// so we have to create an adapter struct like this.
class CElement extends ffi.Struct {
  @ffi.Int32()
  external int _0;

  external ffi.Pointer<ffi.Void> _1;
}

/// Wrapper over Rust's slice type.
///
/// The main functionality comes from [rust_slice_to_c], a function
/// that converts Rust slices into Slice pointers.
///
/// The accompanying `impl_slice_destructor` macro, or the [free_slice]
/// function can be used to define destructors for a particular type.
///
/// It is highly unsafe to mutate this slice before it is returned to the Rust side.
class Slice_CElement extends ffi.Struct {
  @ffi.Uint64()
  external int length;

  external ffi.Pointer<CElement> ptr;
}

/// FFI-compatible adapter for [HtmlTag].
class CHtmlTag extends ffi.Struct {
  /// HTML tag.
  @ffi.Int32()
  external int t;

  /// List of children.
  external ffi.Pointer<Slice_CElement> c;

  /// empty or 'text-align: left|center|right'
  @ffi.Int32()
  external int style;

  /// image src
  external ffi.Pointer<ffi.Int8> src;

  /// anchor href
  external ffi.Pointer<ffi.Int8> href;

  /// for checkbox only
  @ffi.Uint8()
  external int checked;

  /// for math blocks
  @ffi.Uint8()
  external int display;
}

const int _STDINT_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 33;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int __TIMESIZE = 64;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;

const int true_1 = 1;

const int false_1 = 0;

const int __bool_true_false_are_defined = 1;

typedef _c_parse_markdown = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_parse_markdown_xml = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown_xml = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_parse_markdown_ast = ffi.Pointer<Slice_CElement> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown_ast = ffi.Pointer<Slice_CElement> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_free_elements = ffi.Void Function(
  ffi.Pointer<Slice_CElement> ptr,
);

typedef _dart_free_elements = void Function(
  ffi.Pointer<Slice_CElement> ptr,
);

typedef _c_parse_markdown_ast_json = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown_ast_json = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_free_string = ffi.Void Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_free_string = void Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_as_text = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<CElement> el,
);

typedef _dart_as_text = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<CElement> el,
);

typedef _c_as_tag = ffi.Pointer<CHtmlTag> Function(
  ffi.Pointer<CElement> el,
);

typedef _dart_as_tag = ffi.Pointer<CHtmlTag> Function(
  ffi.Pointer<CElement> el,
);
