// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to the Rust library
class MarkdownRust {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MarkdownRust(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MarkdownRust.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void __va_start(
    ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
  ) {
    return ___va_start(
      arg0,
    );
  }

  late final ___va_start_ptr =
      _lookup<ffi.NativeFunction<_c___va_start>>('__va_start');
  late final _dart___va_start ___va_start =
      ___va_start_ptr.asFunction<_dart___va_start>();

  void __security_init_cookie() {
    return ___security_init_cookie();
  }

  late final ___security_init_cookie_ptr =
      _lookup<ffi.NativeFunction<_c___security_init_cookie>>(
          '__security_init_cookie');
  late final _dart___security_init_cookie ___security_init_cookie =
      ___security_init_cookie_ptr.asFunction<_dart___security_init_cookie>();

  void __security_check_cookie(
    int _StackCookie,
  ) {
    return ___security_check_cookie(
      _StackCookie,
    );
  }

  late final ___security_check_cookie_ptr =
      _lookup<ffi.NativeFunction<_c___security_check_cookie>>(
          '__security_check_cookie');
  late final _dart___security_check_cookie ___security_check_cookie =
      ___security_check_cookie_ptr.asFunction<_dart___security_check_cookie>();

  void __report_gsfailure(
    int _StackCookie,
  ) {
    return ___report_gsfailure(
      _StackCookie,
    );
  }

  late final ___report_gsfailure_ptr =
      _lookup<ffi.NativeFunction<_c___report_gsfailure>>('__report_gsfailure');
  late final _dart___report_gsfailure ___report_gsfailure =
      ___report_gsfailure_ptr.asFunction<_dart___report_gsfailure>();

  late final ffi.Pointer<ffi.Uint64> ___security_cookie =
      _lookup<ffi.Uint64>('__security_cookie');

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  /// Parses a Markdown string and returns a JSON string of the AST.
  /// The returned pointer should be freed by [free_string].
  ffi.Pointer<ffi.Int8> parse_markdown(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown(
      ptr,
    );
  }

  late final _parse_markdown_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown>>('parse_markdown');
  late final _dart_parse_markdown _parse_markdown =
      _parse_markdown_ptr.asFunction<_dart_parse_markdown>();

  /// Parses a Markdown string and returns HTML.
  /// The returned pointer should be freed by [free_string].
  ffi.Pointer<ffi.Int8> parse_markdown_xml(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown_xml(
      ptr,
    );
  }

  late final _parse_markdown_xml_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown_xml>>('parse_markdown_xml');
  late final _dart_parse_markdown_xml _parse_markdown_xml =
      _parse_markdown_xml_ptr.asFunction<_dart_parse_markdown_xml>();

  /// Parses a Markdown string and returns a list of [CElement]s.
  /// The returned pointer should be freed by [free_elements].
  ffi.Pointer<Slice_CElement> parse_markdown_ast(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown_ast(
      ptr,
    );
  }

  late final _parse_markdown_ast_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown_ast>>('parse_markdown_ast');
  late final _dart_parse_markdown_ast _parse_markdown_ast =
      _parse_markdown_ast_ptr.asFunction<_dart_parse_markdown_ast>();

  /// Frees the [Slice] created by [parse_markdown_ast].
  void free_elements(
    ffi.Pointer<Slice_CElement> ptr,
  ) {
    return _free_elements(
      ptr,
    );
  }

  late final _free_elements_ptr =
      _lookup<ffi.NativeFunction<_c_free_elements>>('free_elements');
  late final _dart_free_elements _free_elements =
      _free_elements_ptr.asFunction<_dart_free_elements>();

  /// Similar to [parse_markdown], but uses the algorithm from [parse_markdown_ast].
  /// The returned pointer should be freed by [free_string].
  ffi.Pointer<ffi.Int8> parse_markdown_ast_json(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _parse_markdown_ast_json(
      ptr,
    );
  }

  late final _parse_markdown_ast_json_ptr =
      _lookup<ffi.NativeFunction<_c_parse_markdown_ast_json>>(
          'parse_markdown_ast_json');
  late final _dart_parse_markdown_ast_json _parse_markdown_ast_json =
      _parse_markdown_ast_json_ptr.asFunction<_dart_parse_markdown_ast_json>();

  /// Common string destructor intended to be called by the Dart side.
  void free_string(
    ffi.Pointer<ffi.Int8> ptr,
  ) {
    return _free_string(
      ptr,
    );
  }

  late final _free_string_ptr =
      _lookup<ffi.NativeFunction<_c_free_string>>('free_string');
  late final _dart_free_string _free_string =
      _free_string_ptr.asFunction<_dart_free_string>();

  /// Exposes the [CElement] as a text node if it is one, or null otherwise.
  ffi.Pointer<ffi.Int8> as_text(
    ffi.Pointer<CElement> el,
  ) {
    return _as_text(
      el,
    );
  }

  late final _as_text_ptr = _lookup<ffi.NativeFunction<_c_as_text>>('as_text');
  late final _dart_as_text _as_text = _as_text_ptr.asFunction<_dart_as_text>();

  /// Exposes the [CElement] as a [CHtmlTag] if it is one, or null otherwise.
  ffi.Pointer<CHtmlTag> as_tag(
    ffi.Pointer<CElement> el,
  ) {
    return _as_tag(
      el,
    );
  }

  late final _as_tag_ptr = _lookup<ffi.NativeFunction<_c_as_tag>>('as_tag');
  late final _dart_as_tag _as_tag = _as_tag_ptr.asFunction<_dart_as_tag>();
}

/// Tag for [CElement].
abstract class CTag {
  /// [Element::Text]
  static const int Text = 0;

  /// [Element::Tag]
  static const int Tag = 1;
}

abstract class Tags {
  static const int Paragraph = 0;
  static const int H1 = 1;
  static const int H2 = 2;
  static const int H3 = 3;
  static const int H4 = 4;
  static const int H5 = 5;
  static const int H6 = 6;
  static const int Blockquote = 7;
  static const int Pre = 8;
  static const int OrderedList = 9;
  static const int UnorderedList = 10;
  static const int ListItem = 11;
  static const int Table = 12;
  static const int TableRow = 13;
  static const int TableCell = 14;
  static const int TableHeaderCell = 15;
  static const int Emphasis = 16;
  static const int Strong = 17;
  static const int Strikethrough = 18;
  static const int Anchor = 19;
  static const int Image = 20;
  static const int Code = 21;
  static const int HardBreak = 22;
  static const int Ruler = 23;
  static const int Checkbox = 24;
  static const int Math = 25;
}

abstract class TextAlign {
  static const int None = 0;
  static const int Left = 1;
  static const int Center = 2;
  static const int Right = 3;
}

/// Dart does not support enum strcts (20210721),
/// so we have to create an adapter struct like this.
class CElement extends ffi.Struct {
  @ffi.Int32()
  external int _0;

  external ffi.Pointer<ffi.Void> _1;
}

/// Wrapper over Rust's slice type.
///
/// The main functionality comes from [rust_slice_to_c], a function
/// that converts Rust slices into Slice pointers.
///
/// The accompanying `impl_slice_destructor` macro, or the [free_slice]
/// function can be used to define destructors for a particular type.
///
/// It is highly unsafe to mutate this slice before it is returned to the Rust side.
class Slice_CElement extends ffi.Struct {
  @ffi.Uint64()
  external int length;

  external ffi.Pointer<CElement> ptr;
}

/// FFI-compatible adapter for [HtmlTag].
class CHtmlTag extends ffi.Struct {
  /// HTML tag.
  @ffi.Int32()
  external int t;

  /// List of children.
  external ffi.Pointer<Slice_CElement> c;

  /// empty or 'text-align: left|center|right'
  @ffi.Int32()
  external int style;

  /// image src
  external ffi.Pointer<ffi.Int8> src;

  /// anchor href
  external ffi.Pointer<ffi.Int8> href;

  /// for checkbox only
  @ffi.Uint8()
  external int checked;

  /// for math blocks
  @ffi.Uint8()
  external int display;
}

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_NODISCARD = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const int __bool_true_false_are_defined = 1;

const int false_1 = 0;

const int true_1 = 1;

typedef _c___va_start = ffi.Void Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
);

typedef _dart___va_start = void Function(
  ffi.Pointer<ffi.Pointer<ffi.Int8>> arg0,
);

typedef _c___security_init_cookie = ffi.Void Function();

typedef _dart___security_init_cookie = void Function();

typedef _c___security_check_cookie = ffi.Void Function(
  ffi.Uint64 _StackCookie,
);

typedef _dart___security_check_cookie = void Function(
  int _StackCookie,
);

typedef _c___report_gsfailure = ffi.Void Function(
  ffi.Uint64 _StackCookie,
);

typedef _dart___report_gsfailure = void Function(
  int _StackCookie,
);

typedef _c_parse_markdown = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_parse_markdown_xml = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown_xml = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_parse_markdown_ast = ffi.Pointer<Slice_CElement> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown_ast = ffi.Pointer<Slice_CElement> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_free_elements = ffi.Void Function(
  ffi.Pointer<Slice_CElement> ptr,
);

typedef _dart_free_elements = void Function(
  ffi.Pointer<Slice_CElement> ptr,
);

typedef _c_parse_markdown_ast_json = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_parse_markdown_ast_json = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_free_string = ffi.Void Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _dart_free_string = void Function(
  ffi.Pointer<ffi.Int8> ptr,
);

typedef _c_as_text = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<CElement> el,
);

typedef _dart_as_text = ffi.Pointer<ffi.Int8> Function(
  ffi.Pointer<CElement> el,
);

typedef _c_as_tag = ffi.Pointer<CHtmlTag> Function(
  ffi.Pointer<CElement> el,
);

typedef _dart_as_tag = ffi.Pointer<CHtmlTag> Function(
  ffi.Pointer<CElement> el,
);
